export const errorCodes = {
  FQR_NOT_FOUND: 'FQR_NOT_FOUND',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
};
