export const errorCodes = {
  FQR_NOT_FOUND: 'FQR_NOT_FOUND',
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
  EMAIL_CONNECTION_LOST: 'EMAIL_CONNECTION_LOST',
  RFQ_NOT_FOUND: 'RFQ_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
};
